# When reading from the database and returning the data, the columns need to be renamed using this format
COLUMN_CONVERSION_MAP_FROM_DATABASE = {
    "inst_id": "inst_id",
    "institution_name": "Institution name",
    "main_panel": "Main panel",
    "unit_of_assessment_number": "Unit of assessment number",
    "unit_of_assessment_name": "Unit of assessment name",
    "multiple_submission_letter": "Multiple submission letter",
    "multiple_submission_name": "Multiple submission name",
    "joint_submission": "Joint submission",
    "ref_impact_case_study_identifier": "REF impact case study identifier",
    "title": "Title",
    "is_continued_from_2014": "Is continued from 2014",
    "summary_impact_type": "Summary impact type",
    "countries": "Countries",
    "formal_partners": "Formal partners",
    "funding_programmes": "Funding programmes",
    "global_research_identifiers": "Global research identifiers",
    "name_of_funders": "Name of funders",
    "researcher_orcids": "Researcher ORCIDs",
    "grant_funding": "Grant funding",
    "summary_of_the_impact": "1. Summary of the impact",
    "underpinning_research": "2. Underpinning research",
    "references_to_the_research": "3. References to the research",
    "details_of_the_impact": "4. Details of the impact",
    "sources_to_corroborate_the_impact": "5. Sources to corroborate the impact",
    "covid_statement": "COVID-19 Statement",
    "fte": "fte",
    "num_doc_degrees_total": "num_doc_degrees_total",
    "av_income": "av_income",
    "tot_income": "tot_income",
    "tot_inc_kind": "tot_inc_kind",
    "ics_gpa": "ICS_GPA",
    "environment_gpa": "Environment_GPA",
    "output_gpa": "Output_GPA",
    "overall_gpa": "Overall_GPA",
    "post_code": "Post Code",
    "inst_postcode_district": "inst_postcode_district",
    "inst_postcode_area": "inst_postcode_area",
    "ics_url": "ics_url",
    "countries_extracted": "countries_extracted",
    "region_extracted": "region_extracted",
    "union_extracted": "union_extracted",
    "funders_extracted": "funders_extracted",
    "underpinning_research_subject_tag_values": "Underpinning research subject tag values",
    "underpinning_research_subject_tag_group": "Underpinning research subject tag group",
    "uk_region_tag_values": "UK Region tag values",
    "uk_region_tag_group": "UK Region tag group",
    "scientometric_data": "scientometric_data",
    "bert_topic": "BERT_topic",
    "bert_prob": "BERT_prob",
    "bert_topic_terms": "BERT_topic_terms",
    "bert_topic_term_1": "BERT_topic_term_1",
    "bert_topic_term_2": "BERT_topic_term_2",
    "bert_topic_term_3": "BERT_topic_term_3",
    "bert_topic_term_4": "BERT_topic_term_4",
    "bert_topic_term_5": "BERT_topic_term_5",
    "bert_topic_term_6": "BERT_topic_term_6",
    "bert_topic_term_7": "BERT_topic_term_7",
    "bert_topic_term_8": "BERT_topic_term_8",
    "bert_topic_term_9": "BERT_topic_term_9",
    "bert_topic_term_10": "BERT_topic_term_10",
    "max_prob": "max_prob",
    "reassigned": "reassigned",
    "reassignment": "reassignment",
    "final_topic": "final_topic",
    "reassignment_notes": "reassignment_notes",
    "topic_id": "topic_id",
    "cluster_id": "cluster_id",
    "topic_name": "topic_name",
    "topic_name_short": "topic_name_short",
    "cluster_name": "cluster_name",
    "cluster_name_short": "cluster_name_short",
    "topic_description": "topic_description",
    "s1_flesch_score": "s1_flesch_score",
    "s2_flesch_score": "s2_flesch_score",
    "s3_flesch_score": "s3_flesch_score",
    "s4_flesch_score": "s4_flesch_score",
    "s5_flesch_score": "s5_flesch_score",
    "flesch_score": "flesch_score",
    "s1_np_count": "s1_np_count",
    "s1_vp_count": "s1_vp_count",
    "s2_np_count": "s2_np_count",
    "s2_vp_count": "s2_vp_count",
    "s3_np_count": "s3_np_count",
    "s3_vp_count": "s3_vp_count",
    "s4_np_count": "s4_np_count",
    "s4_vp_count": "s4_vp_count",
    "s5_np_count": "s5_np_count",
    "s5_vp_count": "s5_vp_count",
    "s1_sentiment_score": "s1_sentiment_score",
    "s2_sentiment_score": "s2_sentiment_score",
    "s3_sentiment_score": "s3_sentiment_score",
    "s4_sentiment_score": "s4_sentiment_score",
    "s5_sentiment_score": "s5_sentiment_score",
    "sentiment_score": "sentiment_score",
    "ics_id": "REF impact case study identifier",
    "countries_iso3": "countries_extracted",
    "ukprn": "inst_id",
    "uoa": "Unit of assessment number",
    "postcode": "inst_postcode_area"
}