"""
Generate short abbreviations for funders and output as JS const.
Known acronyms take priority; everything else gets initials of significant words.
"""

import csv
import json
import re
from pathlib import Path

KNOWN = {
    "Engineering and Physical Sciences Research Council": "EPSRC",
    "Engineering and Physical Sciences Research Council [GBR]": "EPSRC",
    "Medical Research Council": "MRC",
    "Medical Research Council (MRC)": "MRC",
    "Medical Research Council [GBR]": "MRC",
    "MRC (Medical Research Council)": "MRC",
    "Economic and Social Research Council": "ESRC",
    "Economic and Social Research Council [GBR]": "ESRC",
    "Arts and Humanities Research Council": "AHRC",
    "Arts and Humanities Research Council [GBR]": "AHRC",
    "Arts Humanities Research Council": "AHRC",
    "Natural Environment Research Council": "NERC",
    "Natural Environment Research Council [GBR]": "NERC",
    "Natural Environment Research Council (NERC) (via ESPA)": "NERC",
    "Biotechnology and Biological Sciences Research Council": "BBSRC",
    "Biotechnology and Biological Sciences Research Council [GBR]": "BBSRC",
    "Science and Technology Facilities Council": "STFC",
    "Science and Technologies Facilities Council": "STFC",
    "Science and Technology Facilities Council [GBR]": "STFC",
    "Cancer Research UK": "CRUK",
    "Cancer Research UK [GBR]": "CRUK",
    "Cancer Research UK (Catalyst Award)": "CRUK",
    "Wellcome Trust": "Wellcome",
    "Wellcome Trust and Department of Health": "Wellcome/DoH",
    "Wellcome Collection": "Wellcome Coll",
    "British Heart Foundation": "BHF",
    "National Institute for Health Research": "NIHR",
    "National Institute for Health and Care Research": "NIHR",
    "National Institute for Health and Care Research [GBR]": "NIHR",
    "Innovate UK": "Innovate UK",
    "Innovate UK [GBR]": "Innovate UK",
    "European Research Council": "ERC",
    "European Research Council [EU]": "ERC",
    "European Commission": "EC",
    "European Commission [EU]": "EC",
    "European Union": "EU",
    "European Union [EU]": "EU",
    "Bill and Melinda Gates Foundation": "Gates Fdn",
    "Bill & Melinda Gates Foundation": "Gates Fdn",
    "Leverhulme Trust": "Leverhulme",
    "Leverhulme Trust Trust": "Leverhulme",
    "Leverhume Trust": "Leverhulme",
    "Nuffield Foundation": "Nuffield Fdn",
    "Nuffield Trust": "Nuffield Trust",
    "Nuffield Health": "Nuffield Hlth",
    "Wolfson Foundation": "Wolfson Fdn",
    "Royal Society": "Royal Soc",
    "Royal Society [GBR] Wolfson Fellowship": "Royal Soc",
    "British Academy": "BA",
    "British Academy [GBR]": "BA",
    "British Council": "British Council",
    "National Health Service": "NHS",
    "National Health Service [GBR]": "NHS",
    "Department of Health": "DoH",
    "Department of Health and Social Care": "DHSC",
    "Department of Health and Social Care [GBR]": "DHSC",
    "Department of Health and Public Health Agency": "DoH/PHA",
    "Department of Health and Public Health Agency [GBR]": "DoH/PHA",
    "UK Research and Innovation": "UKRI",
    "UK Research and Innovation [GBR]": "UKRI",
    "Higher Education Funding Council for England": "HEFCE",
    "HEFCE": "HEFCE",
    "Higher Education Funding Council for Wales": "HEFCW",
    "Higher Education Innovation Fund": "HEIF",
    "Higher Education Innovation Fund (HEIF)": "HEIF",
    "Higher Education Innovation Fund [GBR]": "HEIF",
    "Scottish Funding Council": "SFC",
    "Scottish Funding Council SFC": "SFC",
    "Research England": "Research Eng",
    "Research England and SWRI": "Res Eng/SWRI",
    "Joseph Rowntree Foundation": "JRF",
    "Joseph Roundtree Foundation": "JRF",
    "Joseph Rowantree Foundation": "JRF",
    "Charities Aid Foundation": "CAF",
    "Comic Relief": "Comic Relief",
    "Big Lottery Fund": "Big Lottery",
    "Big Lottery": "Big Lottery",
    "The Big Lottery": "Big Lottery",
    "National Lottery Heritage Fund": "NLHF",
    "National Lottery Heritage Found": "NLHF",
    "National Community Lottery Fund": "Nat Lottery",
    "Heritage Lottery": "Heritage Lottery",
    "Alzheimer's Society": "Alz Soc",
    "Alzheimer's Research": "Alz Research",
    "Alzheimer's Research Trust": "Alz Res Trust",
    "Alzheimer's Association": "Alz Assoc",
    "Prostate Cancer UK": "PCUK",
    "Prostate Cancer Research Foundation": "PCRF",
    "Prostate Cancer Foundation": "PCF",
    "Prostate Research Campaign UK": "PRCA",
    "Kidney Research UK": "KRUK",
    "Breast Cancer Campaign": "BCC",
    "Breakthrough Breast Cancer (now Breast Cancer Now)": "BCN",
    "Blood Cancer UK": "BCUK",
    "Bloodwise": "Bloodwise",
    "Pancreatic Cancer UK": "PCUK",
    "Brain Tumour Charity": "Brain Tumour",
    "Motor Neurone Disease Association": "MNDA",
    "MOTOR NEURONE DISEASE ASSOCIATION": "MNDA",
    "MS Society": "MS Soc",
    "Parkinson's UK": "Parkinson's",
    "Cure Parkinson's Trust": "Cure Park",
    "Epilepsy Research UK": "Epilepsy UK",
    "Epilepsy Research Foundation": "Epilepsy Fdn",
    "Autism Speaks": "Autism Speaks",
    "Autism Speaks Foundation": "Autism Speaks",
    "Autistica": "Autistica",
    "National Science Foundation": "NSF",
    "National Science Foundation [USA]": "NSF",
    "National Institutes of Health": "NIH",
    "National Institute of Health [USA]": "NIH",
    "NIH USA": "NIH",
    "Centers for Disease Control and Prevention": "CDC",
    "Centers for Disease Control and Prevention [USA]": "CDC",
    "Department of Energy [USA]": "DoE (US)",
    "Department of Defense [USA]": "DoD (US)",
    "Department of Homeland Security [USA]": "DHS",
    "US Department of Defense": "DoD (US)",
    "US National Cancer Institute": "NCI",
    "National Cancer Institute": "NCI",
    "US National Institute of Justice": "NIJ",
    "US Fish and Wildlife Service": "USFWS",
    "US Fish and Wildlife Service International": "USFWS",
    "World Health Organization": "WHO",
    "World Health Organization [WHO]": "WHO",
    "United Nations": "UN",
    "United Nations [UN]": "UN",
    "United Nations Children's Fund [UN]": "UNICEF",
    "United Nations Educational, Scientific and Cultural Organization [UN]": "UNESCO",
    "United Nations Food and Agriculture Organisation [UN]": "FAO",
    "United Nations Population Fund [UN]": "UNFPA",
    "World Bank": "World Bank",
    "International Monetary Fund": "IMF",
    "Organisation for Economic Co-operation and Development": "OECD",
    "Organisation for Economic Co-operation and Development [OECD]": "OECD",
    "Médecins Sans Frontières": "MSF",
    "Médecins Sans Frontières'": "MSF",
    "Save the Children": "Save Child",
    "Oxfam": "Oxfam",
    "GlaxoSmithKline": "GSK",
    "GlaxoSmithkline": "GSK",
    "GlaxoWellcome": "GlaxoWell",
    "Pfizer": "Pfizer",
    "Novartis": "Novartis",
    "Novartis Pharma AG": "Novartis",
    "Novartis Pharmaceuticals": "Novartis",
    "NovartisPharmaceuticals": "Novartis",
    "Novo Nordisk": "Novo Nordisk",
    "Novo Nordisk A/S": "Novo Nordisk",
    "NovoNordisk": "Novo Nordisk",
    "AstraZeneca": "AZ",
    "Sanofi": "Sanofi",
    "Sanofi-Aventis": "Sanofi",
    "Sanofi Aventis": "Sanofi",
    "Merck": "Merck",
    "Merck KGaA": "Merck KGaA",
    "Merck Sharp & Dohme": "MSD",
    "Merck & Co": "Merck",
    "MSD Animal Health": "MSD AH",
    "AbbVie": "AbbVie",
    "Amgen": "Amgen",
    "Bayer AG": "Bayer",
    "Bayer Healthcare": "Bayer",
    "Bayer Pharma AG": "Bayer",
    "Roche": "Roche",
    "Roche Product": "Roche",
    "Bristol Myers Squibb": "BMS",
    "Johnson & Johnson": "J&J",
    "Johnson & Johnson Vision Care": "J&J Vision",
    "UCB Pharma": "UCB",
    "Alnylam": "Alnylam",
    "Orchard Therapeutics": "Orchard",
    "Gilead Sciences Europe": "Gilead",
    "Vertex Pharmaceuticals": "Vertex",
    "Actelion": "Actelion",
    "AbbVie": "AbbVie",
    "Boehringer Ingelheim": "BI",
    "Boehinger Ingelheim": "BI",
    "Boeringer Ingelheim Vemedica GmbH": "BI",
    "BAE Systems": "BAE",
    "Rolls-Royce": "RR",
    "Thales": "Thales",
    "Airbus": "Airbus",
    "Boeing": "Boeing",
    "Siemens": "Siemens",
    "Microsoft": "Microsoft",
    "Google DeepMind": "DeepMind",
    "OpenAI": "OpenAI",
    "Intel Corporation": "Intel",
    "IBM": "IBM",
    "Huawei Technologies": "Huawei",
    "Tesco": "Tesco",
    "Marks and Spencer": "M&S",
    "Barclays": "Barclays",
    "Santander": "Santander",
    "HSBC": "HSBC",
    "KPMG": "KPMG",
    "Deloitte": "Deloitte",
    "Transport for London": "TfL",
    "Network Rail": "Network Rail",
    "National Grid": "Nat Grid",
    "British Gas": "British Gas",
    "EDF Energy": "EDF",
    "BP Chemicals": "BP",
    "Shell": "Shell",
    "Chevron": "Chevron",
    "Scottish Government": "Scot Gov",
    "Scottish Government Health Directorate": "Scot Gov",
    "Scottish Government Active Scotland Division": "Scot Gov",
    "Scottish Government Legacy 2014": "Scot Gov",
    "Welsh Government": "Welsh Gov",
    "Welsh government": "Welsh Gov",
    "Welsh Assembly Government": "Welsh Gov",
    "UK Cabinet Office": "Cabinet Off",
    "UK Foreign and Commonwealth Office": "FCO",
    "Foreign and Commonwealth Office": "FCO",
    "Foreign, Commonwealth and Development Office": "FCDO",
    "Foreign, Commonwealth and Development Office [GBR]": "FCDO",
    "Ministry of Defence [GBR]": "MoD",
    "Department for International Development [GBR]": "DFID",
    "Department for Business, Energy and Industrial Strategy [GBR]": "BEIS",
    "Department for Business Energy & Industrial Strategy": "BEIS",
    "Department for Environment, Food and Rural Affairs [GBR]": "DEFRA",
    "Department for Digital, Culture, Media and Sport [GBR]": "DCMS",
    "Department for Transport [GBR]": "DfT",
    "Department for Levelling Up, Housing and Communities [GBR]": "DLUHC",
    "Department for Children, Schools and Families [GBR]": "DCSF",
    "Department for Business Innovation and Skills": "BIS",
    "Department for Trade and Industry": "DTI",
    "Office for Students [GBR]": "OfS",
    "Food Standards Agency": "FSA",
    "Food Standards Agency Wales": "FSA Wales",
    "Food Standards Agency, NI": "FSA NI",
    "Food Standards Agency Scotland": "FSA Scot",
    "Food Standards Scotland": "FSA Scot",
    "Public Health England": "PHE",
    "Public Health Scotland": "PH Scotland",
    "Public Health Wales": "PH Wales",
    "Public Health Agency, NI": "PHA NI",
    "European Science Foundation": "ESF",
    "European Space Agency": "ESA",
    "European Medicines Agency": "EMA",
    "European Food Safety Authority": "EFSA",
    "North Sea Transition Deal": "NSTD",
    "Innovate UK, IBM": "Innovate UK",
    "Horizon 2020": "H2020",
    "Seventh Framework Programme [EU]": "FP7",
    "Fifth Framework Programme [EU]": "FP5",
    "CleanSky2 [EU]": "CleanSky2",
    "Fast Track to Innovation [EU]": "FTI",
    "Erasmus [EU]": "Erasmus",
    "Darwin Initiative": "Darwin Init",
    "Darwin Plus": "Darwin Plus",
    "Garfield Weston Foundation": "Garfield W",
    "Garfield Weston": "Garfield W",
    "Esmée Fairbairn Foundation": "Esmée FB",
    "Esme Fairbairn Foundation": "Esmée FB",
    "The Esmée Fairbairn Foundation": "Esmée FB",
    "Oak Foundation": "Oak Fdn",
    "Sigrid Rausing Trust": "Sigrid R",
    "John Templeton Foundation": "Templeton",
    "John Templeton World Charity Foundation": "Templeton",
    "John Templeton Research Foundation": "Templeton",
    "Templeton Religion Trust": "Templeton",
    "Templeton Religious Trust": "Templeton",
    "Carnegie Trust for the Universities of Scotland": "Carnegie",
    "Carnegie Corporation": "Carnegie Corp",
    "Carnegie Corporation of New York": "Carnegie Corp",
    "Carnegie UK Trust": "Carnegie UK",
    "Rockefeller": "Rockefeller",
    "Rockefellar Foundation": "Rockefeller",
    "Calouste Gulbenkian Foundation": "Gulbenkian",
    "Ford Foundation": "Ford Fdn",
    "MacArthur Foundation": "MacArthur",
    "Pears Foundation": "Pears Fdn",
    "Wellbeing of Women": "WoW",
    "Tommy's": "Tommy's",
    "Tommy's Charity": "Tommy's",
    "Macmillan Cancer": "Macmillan",
    "MacMillan Cancer Support": "Macmillan",
    "Macmillan Cancer Northern Ireland": "Macmillan NI",
    "Marie Curie": "Marie Curie",
    "Dimbleby Cancer Care": "Dimbleby",
    "Anthony Nolan": "Anthony Nolan",
    "British Lung Foundation": "BLF",
    "The British Lung Foundation": "BLF",
    "British Skin Foundation": "BSF",
    "British Liver Trust": "BLT",
    "Liver Research UK": "Liver UK",
    "Prostate Cancer UK": "PCUK",
    "Global Challenge Research Fund": "GCRF",
    "Global Challenge Research Fund [GBR]": "GCRF",
    "Global Challenges Research Fund [GBR]": "GCRF",
    "GCRF Newton Fund": "GCRF Newton",
    "Newton Fund": "Newton Fund",
    "Netwton Fund": "Newton Fund",
    "British Broadcasting Corporation": "BBC",
    "BBC": "BBC",
    "Channel 4": "Channel 4",
    "Sport England": "Sport England",
    "Sport Wales": "Sport Wales",
    "Sportscotland": "Sportscot",
    "Sport Northern Ireland": "Sport NI",
    "UK Anti-Doping [GBR]": "UKAD",
    "World Anti-Doping Agency": "WADA",
    "International Olympic Committee": "IOC",
    "Ofcom": "Ofcom",
    "Office of Fair Trading": "OFT",
    "Financial Conduct Authority": "FCA",
    "Competition and Markets Authority": "CMA",
    "Health and Safety Executive [GBR]": "HSE",
    "Health and Safety Executive": "HSE",
    "UK Space Agency": "UKSA",
    "Defence and Security Accelerator [GBR]": "DASA",
    "National Cyber Security Centre": "NCSC",
    "Government Communications Headquarters [GBR]": "GCHQ",
    "Diabetes UK": "Diabetes UK",
    "Diabetes and Research (Cedar) Charity": "CEDAR",
    "Juvenile Diabetes Research Foundation": "JDRF",
    "Juvenile Diabetes Research Fund": "JDRF",
    "Arthritis Research UK": "ARUK",
    "Arthritis Research Campaign (now Versus Arthritis)": "ARUK",
    "Arthritis and Rheumatism Council": "ARC",
    "Action on Hearing Loss": "RNID",
    "Royal National Institute of Blind People": "RNIB",
    "Guide Dogs": "Guide Dogs",
    "Barnardo's": "Barnardo's",
    "NSPCC": "NSPCC",
    "Children's Society": "Childrens Soc",
    "Childrens Society": "Childrens Soc",
    "Children's Commissioner for England": "CCE",
    "Save the Children": "Save Child",
    "VSO International": "VSO",
    "Voluntary Service Overseas": "VSO",
    "Age UK": "Age UK",
    "Royal British Legion": "RBL",
    "Forces in Mind Trust": "FiMT",
    "Forces in Mind": "FiMT",
    "National Trust": "Nat Trust",
    "The National Trust": "Nat Trust",
    "English Heritage": "English Her",
    "Historic England": "Hist Eng",
    "Cadw": "Cadw",
    "Arts Council England [GBR]": "ACE",
    "Arts Council of Northern Ireland": "ACNI",
    "Arts Council of Ireland": "Arts Council",
    "Arts council England": "ACE",
    "Creative Scotland": "Creative Scot",
    "British Film Institute": "BFI",
    "Royal Academy [GBR]": "RA",
    "Royal Academy of Engineering [GBR]": "RAEng",
    "Royal Commission for the Exhibition of 1851": "1851 RC",
    "Lloyd's Register Foundation": "Lloyds Reg",
    "Lloyds Register Foundation": "Lloyds Reg",
    "Gatsby Foundation": "Gatsby",
    "Gatsby Charitable Foundation": "Gatsby",
    "Isaac Newton Trust": "Newton Trust",
    "Petroleum Technology Research Centre": "PTRC",
    "UK Water Industry Research": "UKWIR",
    "Water Research Foundation": "WRF",
    "Interreg": "Interreg",
    "Interreg Europe": "Interreg EU",
    "European Agricultural Fund for Rural Development": "EAFRD",
    "European Maritime and Fisheries Fund": "EMFF",
    "European Regional Development Fund": "ERDF",
    "European Commission European Regional Development Fund": "ERDF",
    "European Fund for Strategic Investments": "EFSI",
    "European Union Innovative Medicines Initiative (EU-IMI)": "EU-IMI",
    "Innovative Medicines Initiative": "IMI",
    "Coalition for Epidemic Preparedness Innovations (CEPI)": "CEPI",
    "GAVI": "Gavi",
    "Gavi": "Gavi",
    "Global Fund": "Global Fund",
    "UNITAID": "UNITAID",
    "Medicines for Malaria Venture": "MMV",
    "International AIDS Society": "IAS",
    "International Aids Society": "IAS",
    "UNAIDS": "UNAIDS",
    "International Atomic Energy Agency": "IAEA",
    "International Labour Organization": "ILO",
    "World Trade Organization": "WTO",
    "World Economic Forum": "WEF",
    "International Monetary Fund": "IMF",
    "North Atlantic Treaty Organisation": "NATO",
    "Commonwealth Fund": "Comm Fund",
    "NordForsk": "NordForsk",
    "Netherlands Organisation for Scientific Research": "NWO",
    "The Netherlands Organization for Scientific Research": "NWO",
    "Netherlands Organisation for Health Research and Development": "ZonMw",
    "Swiss National Science Foundation": "SNSF",
    "German Academic Exchange Service": "DAAD",
    "Deutsche Forschungsgemeinschaft": "DFG",
    "Alexander von Humboldt Stiftung": "AvH",
    "Volkswagen Stiftung": "VW Stiftung",
    "Academy of Finland": "AoF",
    "Research Council of Norway": "RCN",
    "The Research Council of Norway": "RCN",
    "Danish Innovation Fund": "Danish IF",
    "Danish Innovation Foundation": "Danish IF",
    "Swedish Research Council": "SRC",
    "National Research Foundation (South Africa)": "NRF (SA)",
    "South African Medical Research Council": "SAMRC",
    "Canadian Institutes for Health Research": "CIHR",
    "Social Sciences and Humanities Research Council of Canada": "SSHRC",
    "Canadian Social Sciences and Humanities Research Council": "SSHRC",
    "Canadian Socian Science and History Research Council": "SSHRC",
    "National Health and Medical Research Council of Australia": "NHMRC",
    "National Health and Medical Research Council [AUS]": "NHMRC",
    "Australian Research Council": "ARC",
    "Japan Society for the Promotion of Science": "JSPS",
    "Japan Society for the Promotion of Science UK": "JSPS",
    "Qatar National Research Fund": "QNRF",
    "Qatar National Library": "QNL",
    "Hong Kong Research Institute of Textiles and Apparel": "HKRITA",
    "Research Grants Council [HKG]": "RGC HK",
    "Natural Science Foundation of China": "NSFC",
    "National Natural Science Foundation of China (NSFC)": "NSFC",
    "Ministry of Science and Technology [CHN]": "MOST (CHN)",
    "CGIAR": "CGIAR",
    "International Food Policy Research Institute": "IFPRI",
    "World Agroforestry Centre": "ICRAF",
    "Wildlife Conservation Society": "WCS",
    "World Wide Fund for Nature": "WWF",
    "Fauna and Flora International": "FFI",
    "Darwin Initiative": "Darwin Init",
    "BirdLife International": "BirdLife",
    "Zoological Society of London": "ZSL",
    "People's Trust for Endangered Species": "PTES",
    "Royal Society for the Protection of Birds": "RSPB",
    "Royal Society for the Prevention of Cruelty to Animals": "RSPCA",
    "Dogs Trust": "Dogs Trust",
    "Kennel Club Charitable Trust": "Kennel Club",
    "British Veterinary Association": "BVA",
    "Higher Education Academy": "HEA",
    "Teach First": "Teach First",
    "Education Endowment Foundation": "EEF",
    "Education Endowment Fund": "EEF",
    "Sutton Trust": "Sutton Trust",
    "The Sutton Trust": "Sutton Trust",
    "Nuffield Foundation": "Nuffield Fdn",
    "British Council": "British Council",
    "British Council and Higher Education Commission of Pakistan": "BC/HEC",
    "Lloyd Cotsen": "Lloyd Cotsen",
    "Paul Mellon Foundation": "Paul Mellon",
    "Paul Mellon Centre": "PM Centre",
    "Andrew Mellon Foundation": "Mellon Fdn",
    "John Simon Guggenheim Memorial Foundation": "Guggenheim",
    "Fulbright UK-US Commission": "Fulbright",
    "British Institute at Ankara (BIAA)": "BIAA",
    "British School of Archaeology in Iraq": "BSAI",
    "Marie Skłodowska-Curie Actions": "MSCA",
    "MSCA Individual Fellowship": "MSCA IF",
    "Horizon Europe": "Horizon EU",
    "Innovate UK [GBR]": "Innovate UK",
    "Economic and Social Research Council [GBR]": "ESRC",
    "Research Councils UK": "RCUK",
    "UK Research and Innovation [GBR]": "UKRI",
}

SKIP_WORDS = {
    "a", "an", "the", "and", "or", "of", "in", "at", "to", "by",
    "for", "with", "on", "from", "into", "via", "its", "de", "la",
    "le", "les", "des", "du", "et", "für", "für", "van", "der",
    "und", "von", "für", "di", "del", "e", "y", "en", "el",
}


def make_abbrev(name: str, max_len: int = 8) -> str:
    """Generate initials-based abbreviation, skipping minor words."""
    # Strip bracketed suffixes like [GBR], [USA], (via ESPA), etc.
    cleaned = re.sub(r"\s*[\[\(][^\]\)]*[\]\)]", "", name).strip()
    # Split on spaces, hyphens, slashes
    parts = re.split(r"[\s\-/&,]+", cleaned)
    initials = "".join(
        p[0].upper()
        for p in parts
        if p and p.lower() not in SKIP_WORDS and p[0].isalpha()
    )
    return initials[:max_len] if initials else cleaned[:max_len]


def load_funders(csv_path: Path) -> list[str]:
    funders = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            val = row.get("funder", "").strip().strip('"')
            if val:
                funders.append(val)
    return funders


def main():
    here = Path(__file__).parent
    csv_path = here.parent / "app" / "data" / "db-data" / "funders.csv"

    funders = load_funders(csv_path)
    print(f"Loaded {len(funders)} funders")

    lookup: dict[str, str] = {}
    # Track abbreviations used only by algorithmic (non-KNOWN) entries for dedup
    algo_abbrev_count: dict[str, int] = {}

    for funder in funders:
        if funder in KNOWN:
            # Known entries always use exact abbreviation; no dedup
            lookup[funder] = KNOWN[funder]
        else:
            base = make_abbrev(funder)
            count = algo_abbrev_count.get(base, 0)
            abbrev = base if count == 0 else f"{base}{count + 1}"
            algo_abbrev_count[base] = count + 1
            lookup[funder] = abbrev

    out_json = here / "funder_abbrevs.json"
    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(lookup, f, ensure_ascii=False, indent=2)

    print(f"Written {len(lookup)} entries to {out_json}")

    # Spot-check a few well-known ones
    for check in [
        "Engineering and Physical Sciences Research Council",
        "Wellcome Trust",
        "Cancer Research UK",
        "Leverhulme Trust",
        "Bill and Melinda Gates Foundation",
    ]:
        if check in lookup:
            print(f"  {check!r} → {lookup[check]!r}")


if __name__ == "__main__":
    main()
