"""Remove small ics table

Revision ID: 07451859cd9b
Revises: 0ad8cf50aa38
Create Date: 2023-07-29 18:57:21.737097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07451859cd9b'
down_revision = '0ad8cf50aa38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ics_id_ics_id', table_name='ics')
    op.drop_table('ics')
    op.create_index('idx_ics_id_ics_id', 'ics_table_for_download', ['id', 'ics_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ics_id_ics_id', table_name='ics_table_for_download')
    op.create_table('ics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ukprn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('ics_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uoa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ics_pkey')
    )
    op.create_index('idx_ics_id_ics_id', 'ics', ['id', 'ics_id'], unique=False)
    # ### end Alembic commands ###
