"""Update geom models srid

Revision ID: 20fac682d028
Revises: 93ffc25020e9
Create Date: 2023-06-25 13:40:25.461704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fac682d028'
down_revision = '93ffc25020e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('layer')
    # op.drop_table('topology')
    op.execute("""ALTER TABLE "PostCodeGeom" ALTER COLUMN geometry TYPE geometry(MULTIPOLYGON, 4326) USING ST_SetSRID(geometry, 4326)""")
    op.execute("""ALTER TABLE "WorldGeometry" ALTER COLUMN geometry TYPE geometry(MULTIPOLYGON, 4326) USING ST_SetSRID(geometry, 4326)""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('topology',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('topology_id_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    # sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='topology_pkey'),
    # sa.UniqueConstraint('name', name='topology_name_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('layer',
    # sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    # sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name='layer_topology_id_fkey'),
    # sa.PrimaryKeyConstraint('topology_id', 'layer_id', name='layer_pkey'),
    # sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name='layer_schema_name_table_name_feature_column_key')
    # )
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    pass
    # ### end Alembic commands ###
