"""drop unused columns from topics table

Revision ID: 31c96c7d063a
Revises: 4e5d21f415db
Create Date: 2023-09-06 17:34:31.494335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c96c7d063a'
down_revision = '4e5d21f415db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'hierarchical_grouping')
    op.drop_column('topics', 'cluster_name')
    op.drop_column('topics', 'topic_notes')
    op.drop_column('topics', 'topic_name_long')
    op.drop_column('topics', 'cluster')
    op.drop_column('topics', 'charlie_suggested')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('charlie_suggested', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('cluster', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('topic_name_long', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('topic_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('cluster_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('hierarchical_grouping', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
