"""Add extra fields to ics table

Revision ID: 3e196e8aaab7
Revises: a4ee7481bb73
Create Date: 2024-01-18 20:04:31.386180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e196e8aaab7'
down_revision = 'a4ee7481bb73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ics', sa.Column('countries_specific_extracted', sa.String(), nullable=True))
    op.add_column('ics', sa.Column('countries_region_extracted', sa.String(), nullable=True))
    op.add_column('ics', sa.Column('countries_union_extracted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ics', 'countries_union_extracted')
    op.drop_column('ics', 'countries_region_extracted')
    op.drop_column('ics', 'countries_specific_extracted')
    # ### end Alembic commands ###
