"""Add uoa column to web text

Revision ID: 4e5d21f415db
Revises: 6cad544a2706
Create Date: 2023-08-13 11:36:57.303597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e5d21f415db'
down_revision = '6cad544a2706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websitetext', sa.Column('uoa_bar_colours', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websitetext', 'uoa_bar_colours')
    # ### end Alembic commands ###
