"""Update field names in WebsiteText

Revision ID: 50d8905d775b
Revises: a1795f8f1492
Create Date: 2023-07-09 17:03:16.275201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d8905d775b'
down_revision = 'a1795f8f1492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websitetext', sa.Column('team', sa.String(), nullable=True))
    op.add_column('websitetext', sa.Column('contact', sa.String(), nullable=True))
    op.drop_column('websitetext', 'Contact')
    op.drop_column('websitetext', 'Team')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websitetext', sa.Column('Team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('websitetext', sa.Column('Contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('websitetext', 'contact')
    op.drop_column('websitetext', 'team')
    # ### end Alembic commands ###
