"""Add fields to website text

Revision ID: 6cad544a2706
Revises: 90ea6aa43a32
Create Date: 2023-08-05 10:25:05.328375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cad544a2706'
down_revision = '90ea6aa43a32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websitetext', sa.Column('uk_map_colourramp', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('websitetext', sa.Column('global_colourramp', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('websitetext', sa.Column('funders_bar_colour', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websitetext', 'funders_bar_colour')
    op.drop_column('websitetext', 'global_colourramp')
    op.drop_column('websitetext', 'uk_map_colourramp')
    # ### end Alembic commands ###
