"""Add global countries extracted fields to ics and countries

Revision ID: 8fbbd4f3ffe8
Revises: cca39d01c464
Create Date: 2024-01-21 19:34:47.858645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbbd4f3ffe8'
down_revision = 'cca39d01c464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('countries_global_extracted', sa.Boolean(), nullable=False, server_default="false"))
    op.add_column('ics', sa.Column('global_extracted', sa.Boolean(), nullable=True))
    op.add_column('ics', sa.Column('countries_global_extracted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ics', 'countries_global_extracted')
    op.drop_column('ics', 'global_extracted')
    op.drop_column('countries', 'countries_global_extracted')
    # ### end Alembic commands ###
