"""Add topic groups table

Revision ID: 90ea6aa43a32
Revises: d5c9acee5f91
Create Date: 2023-08-03 19:56:55.330086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ea6aa43a32'
down_revision = 'd5c9acee5f91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('topic_group', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_groups')
    # ### end Alembic commands ###
