"""Initial migration

Revision ID: 947fefcec248
Revises: 
Create Date: 2023-08-01 19:10:19.996921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947fefcec248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_countries_id', 'countries', ['id'], unique=True)
    op.create_table('funder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=False),
    sa.Column('funder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ics_table_id')
    )
    op.create_index('idx_funder_id', 'funder', ['id'], unique=True)
    op.create_table('ics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('main_panel', sa.String(), nullable=True),
    sa.Column('unit_of_assessment_number', sa.String(), nullable=True),
    sa.Column('unit_of_assessment_name', sa.String(), nullable=True),
    sa.Column('multiple_submission_letter', sa.String(), nullable=True),
    sa.Column('multiple_submission_name', sa.String(), nullable=True),
    sa.Column('joint_submission', sa.String(), nullable=True),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_continued_from_2014', sa.String(), nullable=True),
    sa.Column('summary_impact_type', sa.String(), nullable=True),
    sa.Column('countries', sa.String(), nullable=True),
    sa.Column('formal_partners', sa.String(), nullable=True),
    sa.Column('funding_programmes', sa.String(), nullable=True),
    sa.Column('global_research_identifiers', sa.String(), nullable=True),
    sa.Column('name_of_funders', sa.String(), nullable=True),
    sa.Column('researcher_orcids', sa.String(), nullable=True),
    sa.Column('grant_funding', sa.String(), nullable=True),
    sa.Column('summary_of_the_impact', sa.String(), nullable=True),
    sa.Column('underpinning_research', sa.String(), nullable=True),
    sa.Column('references_to_the_research', sa.String(), nullable=True),
    sa.Column('details_of_the_impact', sa.String(), nullable=True),
    sa.Column('sources_to_corroborate_the_impact', sa.String(), nullable=True),
    sa.Column('covid_statement', sa.String(), nullable=True),
    sa.Column('uoa', sa.Integer(), nullable=True),
    sa.Column('countries_iso3', sa.String(), nullable=True),
    sa.Column('inst_postcode', sa.String(), nullable=True),
    sa.Column('inst_postcode_district', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('ics_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ics_id', 'ics', ['id', 'ics_id'], unique=False)
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topic_weights_id', 'topic_weights', ['id'], unique=True)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('topic_group', sa.String(), nullable=True),
    sa.Column('topic_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('charlie_suggested', sa.String(), nullable=True),
    sa.Column('topic_name_long', sa.String(), nullable=True),
    sa.Column('hierarchical_grouping', sa.String(), nullable=True),
    sa.Column('cluster_name', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('topic_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index('idx_topics_id', 'topics', ['topic_id'], unique=True)
    op.create_table('uoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uoa_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assessment_panel', sa.String(length=1), nullable=False),
    sa.Column('assessment_group', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uoa_id', 'uoa', ['id'], unique=True)
    op.create_table('websitetext',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('all_topics_description', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('label_info_box', sa.String(), nullable=True),
    sa.Column('label_top_left_box', sa.String(), nullable=True),
    sa.Column('label_bottom_left_box', sa.String(), nullable=True),
    sa.Column('label_top_right_box', sa.String(), nullable=True),
    sa.Column('label_bottom_right_box', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websitetext')
    op.drop_index('idx_uoa_id', table_name='uoa')
    op.drop_table('uoa')
    op.drop_index('idx_topics_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_topic_weights_id', table_name='topic_weights')
    op.drop_table('topic_weights')
    op.drop_table('institution')
    op.drop_index('idx_ics_id', table_name='ics')
    op.drop_table('ics')
    op.drop_index('idx_funder_id', table_name='funder')
    op.drop_table('funder')
    op.drop_index('idx_countries_id', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
