"""Add websitetext table

Revision ID: a1795f8f1492
Revises: ff9eaaa78917
Create Date: 2023-07-09 16:53:16.484909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1795f8f1492'
down_revision = 'ff9eaaa78917'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_countries_id', 'countries', ['id'], unique=True)
    op.create_table('funder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=False),
    sa.Column('funder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ics_table_id')
    )
    op.create_index('idx_funder_id', 'funder', ['id'], unique=True)
    op.create_table('ics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('uoa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ics_id_ics_id', 'ics', ['id', 'ics_id'], unique=False)
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topic_weights_id', 'topic_weights', ['id'], unique=True)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=20), nullable=True),
    sa.Column('topic_group', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index('idx_topics_id', 'topics', ['topic_id'], unique=True)
    op.create_table('uoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uoa_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('assessment_panel', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uoa_id', 'uoa', ['id'], unique=True)
    op.create_table('websitetext',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('all_topics_description', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('Team', sa.String(), nullable=True),
    sa.Column('Contact', sa.String(), nullable=True),
    sa.Column('label_info_box', sa.String(), nullable=True),
    sa.Column('label_top_left_box', sa.String(), nullable=True),
    sa.Column('label_bottom_left_box', sa.String(), nullable=True),
    sa.Column('label_top_right_box', sa.String(), nullable=True),
    sa.Column('label_botton_right_box', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websitetext')
    op.drop_index('idx_uoa_id', table_name='uoa')
    op.drop_table('uoa')
    op.drop_index('idx_topics_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_topic_weights_id', table_name='topic_weights')
    op.drop_table('topic_weights')
    op.drop_table('institution')
    op.drop_index('idx_ics_id_ics_id', table_name='ics')
    op.drop_table('ics')
    op.drop_index('idx_funder_id', table_name='funder')
    op.drop_table('funder')
    op.drop_index('idx_countries_id', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
