"""Remake tables intial commit

Revision ID: b5a32a7a65cc
Revises: 
Create Date: 2023-07-30 16:35:19.966763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a32a7a65cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('main_panel', sa.String(), nullable=True),
    sa.Column('unit_of_assessment_number', sa.String(), nullable=True),
    sa.Column('unit_of_assessment_name', sa.String(), nullable=True),
    sa.Column('multiple_submission_letter', sa.String(), nullable=True),
    sa.Column('multiple_submission_name', sa.String(), nullable=True),
    sa.Column('joint_submission', sa.String(), nullable=True),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_continued_from_2014', sa.String(), nullable=True),
    sa.Column('summary_impact_type', sa.String(), nullable=True),
    sa.Column('countries', sa.String(), nullable=True),
    sa.Column('formal_partners', sa.String(), nullable=True),
    sa.Column('funding_programmes', sa.String(), nullable=True),
    sa.Column('global_research_identifiers', sa.String(), nullable=True),
    sa.Column('name_of_funders', sa.String(), nullable=True),
    sa.Column('researcher_orcids', sa.String(), nullable=True),
    sa.Column('grant_funding', sa.String(), nullable=True),
    sa.Column('summary_of_the_impact', sa.String(), nullable=True),
    sa.Column('underpinning_research', sa.String(), nullable=True),
    sa.Column('references_to_the_research', sa.String(), nullable=True),
    sa.Column('details_of_the_impact', sa.String(), nullable=True),
    sa.Column('sources_to_corroborate_the_impact', sa.String(), nullable=True),
    sa.Column('covid_statement', sa.String(), nullable=True),
    sa.Column('uoa', sa.Integer(), nullable=True),
    sa.Column('countries_iso3', sa.String(), nullable=True),
    sa.Column('inst_postcode', sa.String(), nullable=True),
    sa.Column('inst_postcode_district', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('ics_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ics_id', 'ics', ['id', 'ics_id'], unique=False)
    op.drop_index('idx_ics_id_ics_id', table_name='ics_table_for_download')
    op.drop_table('ics_table_for_download')
    op.add_column('websitetext', sa.Column('label_bottom_right_box', sa.String(), nullable=True))
    op.drop_column('websitetext', 'label_botton_right_box')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websitetext', sa.Column('label_botton_right_box', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('websitetext', 'label_bottom_right_box')
    op.create_table('ics_table_for_download',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ukprn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('institution_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main_panel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit_of_assessment_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit_of_assessment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('multiple_submission_letter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('multiple_submission_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('joint_submission', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ics_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_continued_from_2014', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary_impact_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('countries', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('formal_partners', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('funding_programmes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('global_research_identifiers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('funders', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('researcher_orcids', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grant_funding', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary_of_the_impact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('underpinning_research', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('references_to_the_research', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('details_of_the_impact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sources_to_corroborate_the_impact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('covid_statement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uoa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary_of_the_impact_topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cultural', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('economic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('environmental', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('health', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('legal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('political', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('societal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technological', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inst_postcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inst_postcode_district', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ics_table_for_download_pkey')
    )
    op.create_index('idx_ics_id_ics_id', 'ics_table_for_download', ['id', 'ics_id'], unique=False)
    op.drop_index('idx_ics_id', table_name='ics')
    op.drop_table('ics')
    # ### end Alembic commands ###
