"""Add countries extracted to countries

Revision ID: cca39d01c464
Revises: 3e196e8aaab7
Create Date: 2024-01-20 18:25:15.129610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca39d01c464'
down_revision = '3e196e8aaab7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('countries_specific_extracted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('countries', sa.Column('countries_union_extracted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('countries', sa.Column('countries_region_extracted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'countries_region_extracted')
    op.drop_column('countries', 'countries_union_extracted')
    op.drop_column('countries', 'countries_specific_extracted')
    # ### end Alembic commands ###
