"""Add topic_group_long to topic_groups model

Revision ID: d5c849524458
Revises: 974ccd364e77
Create Date: 2023-12-27 12:31:06.845526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c849524458'
down_revision = '974ccd364e77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_groups', sa.Column('topic_group_long', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_groups', 'topic_group_long')
    # ### end Alembic commands ###
