"""Remove small ics table

Revision ID: d8afdfeadbff
Revises: 07451859cd9b
Create Date: 2023-07-29 19:06:04.568033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8afdfeadbff'
down_revision = '07451859cd9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
