"""Initial migration

Revision ID: eb3e632ce6c4
Revises: 
Create Date: 2023-07-05 19:29:06.436485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3e632ce6c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_countries_id', 'Countries', ['id'], unique=True)
    op.create_table('Funder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=False),
    sa.Column('funder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ics_table_id')
    )
    op.create_index('idx_funder_id', 'Funder', ['id'], unique=True)
    op.create_table('ICS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('uoa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ics_id_ics_id', 'ICS', ['id', 'ics_id'], unique=False)
    op.create_table('Institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Topic_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topic_weights_id', 'Topic_weights', ['id'], unique=True)
    op.create_table('Topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=20), nullable=True),
    sa.Column('topic_group', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index('idx_topics_id', 'Topics', ['topic_id'], unique=True)
    op.create_table('UOA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uoa_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uoa_id', 'UOA', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uoa_id', table_name='UOA')
    op.drop_table('UOA')
    op.drop_index('idx_topics_id', table_name='Topics')
    op.drop_table('Topics')
    op.drop_index('idx_topic_weights_id', table_name='Topic_weights')
    op.drop_table('Topic_weights')
    op.drop_table('Institution')
    op.drop_index('idx_ics_id_ics_id', table_name='ICS')
    op.drop_table('ICS')
    op.drop_index('idx_funder_id', table_name='Funder')
    op.drop_table('Funder')
    op.drop_index('idx_countries_id', table_name='Countries')
    op.drop_table('Countries')
    # ### end Alembic commands ###
