"""Change __tablename__ to lowercase

Revision ID: ff9eaaa78917
Revises: eb3e632ce6c4
Create Date: 2023-07-05 19:39:31.181402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9eaaa78917'
down_revision = 'eb3e632ce6c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Institution')
    op.drop_index('idx_funder_id', table_name='Funder')
    op.drop_table('Funder')
    op.drop_index('idx_countries_id', table_name='Countries')
    op.drop_table('Countries')
    op.drop_index('idx_uoa_id', table_name='UOA')
    op.drop_table('UOA')
    op.drop_index('idx_ics_id_ics_id', table_name='ICS')
    op.drop_table('ICS')
    op.drop_index('idx_topic_weights_id', table_name='Topic_weights')
    op.drop_table('Topic_weights')
    op.drop_index('idx_topics_id', table_name='Topics')
    op.drop_table('Topics')
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_countries_id', 'countries', ['id'], unique=True)
    op.create_table('funder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_table_id', sa.Integer(), nullable=False),
    sa.Column('funder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'ics_table_id')
    )
    op.create_index('idx_funder_id', 'funder', ['id'], unique=True)
    op.create_table('ics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('uoa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ics_id_ics_id', 'ics', ['id', 'ics_id'], unique=False)
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ukprn', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ics_id', sa.String(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topic_weights_id', 'topic_weights', ['id'], unique=True)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=20), nullable=True),
    sa.Column('topic_group', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index('idx_topics_id', 'topics', ['topic_id'], unique=True)
    op.create_table('uoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uoa_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uoa_id', 'uoa', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Topics',
    sa.Column('topic_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Topics_topic_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('topic_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('narrative', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('topic_id', name='Topics_pkey')
    )
    op.create_index('idx_topics_id', 'Topics', ['topic_id'], unique=False)
    op.create_table('Topic_weights',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Topic_weights_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ics_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Topic_weights_pkey')
    )
    op.create_index('idx_topic_weights_id', 'Topic_weights', ['id'], unique=False)
    op.create_table('ICS',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ICS_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ukprn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('ics_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uoa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ICS_pkey')
    )
    op.create_index('idx_ics_id_ics_id', 'ICS', ['id', 'ics_id'], unique=False)
    op.create_table('UOA',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UOA_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('uoa_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='UOA_pkey')
    )
    op.create_index('idx_uoa_id', 'UOA', ['id'], unique=False)
    op.create_table('Countries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Countries_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ics_table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Countries_pkey')
    )
    op.create_index('idx_countries_id', 'Countries', ['id'], unique=False)
    op.create_table('Funder',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ics_table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funder', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'ics_table_id', name='Funder_pkey')
    )
    op.create_index('idx_funder_id', 'Funder', ['id'], unique=False)
    op.create_table('Institution',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Institution_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ukprn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Institution_pkey')
    )
    op.drop_index('idx_uoa_id', table_name='uoa')
    op.drop_table('uoa')
    op.drop_index('idx_topics_id', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_topic_weights_id', table_name='topic_weights')
    op.drop_table('topic_weights')
    op.drop_table('institution')
    op.drop_index('idx_ics_id_ics_id', table_name='ics')
    op.drop_table('ics')
    op.drop_index('idx_funder_id', table_name='funder')
    op.drop_table('funder')
    op.drop_index('idx_countries_id', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
